// backend/glossaryData.js

// 1. Words to ALWAYS ignore (Stopwords, Months, Common Verbs)
const IGNORED_WORDS = new Set([
    "The",
    "This",
    "That",
    "There",
    "Their",
    "Then",
    "They",
    "With",
    "What",
    "When",
    "Where",
    "Which",
    "While",
    "From",
    "Have",
    "Having",
    "Been",
    "Were",
    "Section",
    "Article",
    "Page",
    "Date",
    "Time",
    "Text",
    "View",
    "Official",
    "General",
    "April",
    "March",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
    "Whereas",
    "After",
    "Before",
    "Union",
    "European",
    "Parliament",
    "Council",
    "Commission",
    "Member",
    "States",
    "Position",
    "Journal",
    "Acting",
    "Functioning",
    "Treaty",
    "Regulation",
    "Directive",
    "Decision",
    "Annex",
    "Chapter",
    "Paragraph",
]);

// 2. Manual Definitions for Acronyms & Legal Terms (API fails on these)
const LEGAL_DICTIONARY = {
    GDPR: "General Data Protection Regulation. A regulation in EU law on data protection and privacy.",
    TFEU: "Treaty on the Functioning of the European Union.",
    EEA: "European Economic Area.",
    EU: "European Union.",
    OJ: "Official Journal of the European Union.",
    Charter: "The Charter of Fundamental Rights of the European Union.",
    Directive:
        "A legal act of the European Union which requires member states to achieve a particular result.",
    Regulation:
        "A legal act of the European Union that becomes immediately enforceable as law in all member states simultaneously.",
    "Force Majeure":
        "Unforeseeable circumstances that prevent someone from fulfilling a contract.",
    NDA: "Non-Disclosure Agreement. A legal contract between at least two parties that outlines confidential material, knowledge, or information.",
};

// Export them so server.js can use them
module.exports = {
    IGNORED_WORDS,
    LEGAL_DICTIONARY,
};
