module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>'],
  testMatch: ['**/__tests__/**/*.test.[jt]s?(x)', '**/?(*.)+(spec).[jt]s?(x)'],
  testPathIgnorePatterns: ['/__tests__/setup.js', '/server.test.js'],
  moduleFileExtensions: ['js', 'json', 'node'],
  collectCoverageFrom: [
    'src/**/*.js',
    'server.js',
    '!**/*.test.js',
    '!**/node_modules/**',
    '!**/__tests__/**',
    '!**/testUtils/**',
    '!**/coverage/**',
    '!jest.config.js',
    '!jest.config.cjs',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 30,
      functions: 38,
      lines: 45,
      statements: 45,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/__tests__/setup.js'],
  testTimeout: 30000,
  clearMocks: true,
  restoreMocks: true,
};
